name: "Run Deployment in prod"
on:
  pull_request_review:
    types: [submitted]
    branches:
      - 'mp-prod-**'
    #paths-ignore:
     # - '.github/**'  

jobs:
  PRODSample:
    if: github.event.review.state == 'approved' && contains(github.ref, 'qa')
    runs-on: ubuntu-latest
    environment:
      name: prod 
    steps:
      - name: Checking out Code from Github
        uses: actions/checkout@v2
      - name: Setting Python Actions
        uses: actions/setup-python@v2
      - name: Sample Hellow
        run: echo "Hello World! form Prod"
      - name: Sample hello
        run: echo "Sample Hello"     
      - name: sample two 
        run : echo "sample hellow worldd!"   
