name: "Run Deployment in qa"
on:
  pull_request_review:
    types: [submitted]
    #branches:
     # - 'mp-qa-**'
    #paths-ignore:
     # - '.github/**'  
    #test wf 1
    #Dave test

jobs:
  QASample:
    if: github.event.review.state == 'approved' && contains(github.event.pull_request.base.ref, 'qa')
    runs-on: ubuntu-latest
    environment:
      name: qa 
    steps:
      - name: Checking out Code from Github
        uses: actions/checkout@v2
      - name: Setting Python Actions
        uses: actions/setup-python@v2
      - name: Sample Hellow
        run: echo "Hello World! From QA"
      - name: Sample hello
        run: echo "Sample Hello"      
