name: "Pull Request with Review"
on:
  pull_request_review:
    types: [submitted]
    branches:
      - main
    #paths-ignore:
     # - '.github/**'  

jobs:
  QASample:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    environment:
      name: QA 
    steps:
      - name: Checking out Code from Github
        uses: actions/checkout@v2
      - name: Setting Python Actions
        uses: actions/setup-python@v2
      - name: Sample Hellow
        run: echo "Hello World! From QA"
      - name: Sample hello
        run: echo "Sample Hello"      
