name: "Run Deployment of mp-product-import in QA"
on:
  pull_request:
    types:
      - edited
      - opened
    branches:
      - 'mp-qa-/**'  
    #paths-ignore:
     # - '.github/**'  

jobs:
  QASample:
    runs-on: ubuntu-latest
    environment:
      name: QA 
    steps:
      - name: Checking out Code from Github
        uses: actions/checkout@v2
      - name: Setting Python Actions
        uses: actions/setup-python@v2
      - name: Sample Hellow
        run: echo "Hello World! From QA"
      - name: Sample hello
        run: echo "Sample Hello"      
